### ISSUE TITLE
OAStackViewAlignmentStrategyCenter does not ensure the stack view is at least as big as the arranged subviews

### ISSUE THREAD

**Issue by Thomvis** [oarrabi/OAStackView#12]
OAStackViewAlignmentStrategyCenter only adds a constraint to center the arranged subviews:

``` objc
@implementation OAStackViewAlignmentStrategyCenter

- (NSArray*)constraintsalignViewOnOtherAxis:(UIView*)view {

  return @[[NSLayoutConstraint constraintWithItem:view
                               attribute:[self centerAttribute]
                               relatedBy:NSLayoutRelationEqual
                                  toItem:view.superview
                               attribute:[self centerAttribute]
                                       multiplier:1 constant:0]];
}

@end
```

but I'd expect it would also make sure that the stack view is large enough to accomodate all arranged subviews. 

If you agree, I'd gladly make a PR for it.

**Comment by Thomvis** [comment]
Looking a bit further, it seems that the intrinsic content size should cover for this. Not an issue then, probably. Sorry about that, feel free to close this.

**Comment by nsomar** [comment]
Ok, will be closing this.
Thanks for your time :+1:
