### ISSUE TITLE
Add normal framework target so this can be installed outside of CocoaPods.

### ISSUE THREAD

**Issue by calebd** [oarrabi/OAStackView#18]

**Comment by ghost** [comment]
Said another way, [Carthage](https://github.com/Carthage/Carthage) support would be great - at present the repo doesn't have an _xcodeproj_ with a framework target to build from.

**Comment by ghost** [comment]
And of course I said that before looking at the PRs, @avalanched's #19 adds an _xcodeproj_ with dynamic framework target to do precisely this. :wink:

**Comment by nsomar** [comment]
@pizthewiz Hey, I just merged pr #19 :+1: 
I will be closing this issue, thanks :)
