### ISSUE TITLE
Control View Order from IB?

### ISSUE THREAD

**Issue by westongpt** [oarrabi/OAStackView#23]
How is view order controlled in interface builder? I have one view that it just wants to keep sticking at the bottom, not matter what I try.

**Comment by davidkobilnyk** [comment]
I had this problem too. It seems to follow the order of the views listed in the Document Outline sidebar on the left in IB. Rearranging my views there fixed things for me. Your view sticking to the bottom might need to be dragged up to a different location. (Incidentally, if you're not aware already, this ordering in IB is usually used for determining which view sits in front of another view, if two views overlap each other.)

![screen shot 2015-07-27 at 3 36 29 pm](https://cloud.githubusercontent.com/assets/1111661/8919624/d8e2b738-3475-11e5-8d1a-3ad3a7942c6e.png)

Hope that helps.

**Comment by nsomar** [comment]
@davidkobilnyk that is correct, the order of the views in the IB is actually reflected in the order of the views in self.subviews.

**Comment by nsomar** [comment]
I will be closing this issue. Please reopen it if there are still concerns about it.
