### ISSUE TITLE
Unknown Type Name 'NS_ASSUME_NONNULL_BEGIN/END'

### ISSUE THREAD

**Issue by ParilShah** [oarrabi/OAStackView#26]
<img width="1392" alt="screen shot 2015-07-16 at 3 35 04 am" src="https://cloud.githubusercontent.com/assets/3435334/8710975/67cc2150-2b6b-11e5-8124-0aa574b21789.png">

**Comment by nsomar** [comment]
Hey, what version of Xcode are you on?

**Comment by ParilShah** [comment]
I am using Xcode 6.2

**Comment by harlanhaskins** [comment]
You need to update to Xcode 6.4.

**Comment by ParilShah** [comment]
Yes, its working fine with even Xcode 6.3.1. If possible then please specify minimum Xcode version in README file. It helps others.
