### ISSUE TITLE
hi why it can not support to ios6?

### ISSUE THREAD

**Issue by wy19901227** [oarrabi/OAStackView#29]
autolayout is from ios6,so can it support to ios6?

**Comment by nsomar** [comment]
Hello, I did not really test it on iOS6, I cannot think of a reason why it shouldnt work. I dont have an iOS 6 simulator running at the moment, It would be amazing if some one tries it on iOS6.

**Comment by harlanhaskins** [comment]
Probably shouldn't make any changes to make it compatible, if it's not already. iOS 6 is a fraction of a fraction of market share right now.

**Comment by nsomar** [comment]
@harlanhaskins I totally agree, I think if OAStackView supports iOS6, then its good, otherwise, I dont think we should make any changes to it

**Comment by nsomar** [comment]
I will be closing this issue, since I think we agree on it.

**Comment by wy19901227** [comment]
I have many ios6 iphone，the demo  doesn't wort well .  It will crash when tap some btton
