### ISSUE TITLE
0.1.0 - Cocoapod's Version Not Working

### ISSUE THREAD

**Issue by coridn** [oarrabi/OAStackView#30]
My specific scenario.

```
View
--UISrollView
----OAStackView (Constrained on all sides, also constrained to equal width of scrollview)
```

At runtime, I need to add views to the stack view.
When I add a single view using `[self.stackView addArrangedSubview:view]`, it works adding that single view.

As soon as I try to add a second view programatically, both views disappear, and the constraints (for the stack view and its subviews), are no longer correct.

Note that this is only specific to the current version on Cocoapods.  If I target the latest commit on master, this is no longer an issue.

Can we have an update to the spec uploaded?

Thanks!

**Comment by harlanhaskins** [comment]
You've got a constraint on all sides of the UIScrollView? Make sure your bottom constraint is >=0, because a UIScrollView doesn't have a size that AutoLayout can actually make use of.

**Comment by coridn** [comment]
@harlanhaskins Doing that causes an ambiguous content height for the scroll view.  I've pasted an image of my constraints.  The height constraint is removed at runtime.  I'm using it to avoid the ambiguous content height warning I still would get by changing the constraint to >= 0.

![screen shot 2015-07-28 at 9 15 07 am](https://cloud.githubusercontent.com/assets/5191060/8932152/2aea59a8-3509-11e5-81c2-99c454825454.png)

I guess I still don't understand how that is the issue when adding a single view to the stackview works, but adding a second view does not.

**Comment by harlanhaskins** [comment]
I'd recommend reading this Apple developer page about using AutoLayout with UIScrollView.

https://developer.apple.com/library/ios/technotes/tn2154/_index.html

**Comment by coridn** [comment]
Aside from my apparently scrollview issues (which work regardless), all I'm asking for is an update to the current cocoapods spec.

**Comment by mthole-old** [comment]
I ran into this exact same problem today using the Pod-installed v0.1.0 of OAStackView. Updating to master by manually specifying the git repo in my Podfile fixed it.

+1 to publishing a new spec with the latest (cc: @oarrabi)

**Comment by delebedev** [comment]
@oarrabi is AFK for a couple of weeks. I've added 0.2.0 tag, so you can refer to it in the meantime.

@oarrabi please add me as a maintainer to pods repo as well when you have a chance:

```
$ pod trunk add-owner OAStackView d2.lebedev@gmail.com
```

**Comment by nsomar** [comment]
I am really sorry for being this late, @garnett I have added you as an owner to the pod.

**Comment by nsomar** [comment]
Closing this issue since it has been solved
