### ISSUE TITLE
Dose OAStackView avoid user interaction?

### ISSUE THREAD

**Issue by dubiao** [oarrabi/OAStackView#34]
I use OAStackView on my menu view. It shows greatly. But my menu items dose not response to my tap
my code :

> itemStack = OAStackView(arrangedSubviews: menuItems)
> addSubview(itemStack)

And I am sure that I added UITapGestureRecognizer to my items

> item.addGestureRecognizer(gestureRecognizer)

And my items'  `item.userInteractionEnabled = true`

I use UIView instead of OAStackView it's tappable.

**Comment by nsomar** [comment]
Hey, I am not aware of such a problem.
Could you please share more info, it would be great if you can supply a very small snippet (or project) that I could run. Thanks

**Comment by nsomar** [comment]
@dubiao  I am closing this issue since there have been no feedback from your side.
Please feel free to reopen it if the issue persists.
