### ISSUE TITLE
Added constant leading/header and trailing/footer padding space?

### ISSUE THREAD

**Issue by komocode** [oarrabi/OAStackView#37]
I would like some padding at the top of the OAStackView before the first view is laid out and space after the last view is laid out. Is it possible to add IBInspectables for them?

**Comment by harlanhaskins** [comment]
You can use layoutMarginsRelativeAlignment. Just set stackView.layoutMarginsRelativeAlignment to true and set `stackView.layoutMargins` to `UIEdgeInsets(top: <value>, left: 0, bottom: <value>, right: 0)`

**Comment by christophercotton** [comment]
@harlanhaskins Except `layoutMargins` is iOS8 only.

**Comment by harlanhaskins** [comment]
Not with OAStackView. OAStackView adds the property for iOS 7 compatibility.

**Comment by christophercotton** [comment]
@harlanhaskins Ah nice! It isn't in the released version of the pod I've been using, but I see the commits. Thanks.

**Comment by delebedev** [comment]
@christophercotton try out 0.2.0 tag (still no new cocoapod version though)
