### ISSUE TITLE
What is the best way to use OAStackView in UITableViewCell with Dynamic Cell Sizing

### ISSUE THREAD

**Issue by ghost** [oarrabi/OAStackView#38]
I am working on a app which have components similar to Facebook Feed, there is User detail, Images, Like & Comment button, Polls etc. Apart from user detail everything is optional. I am using Dynamic cell sizing along with OAStackView and its working good when I am scrolling down. But once I reach the bottom and then scroll up, the scrolling is bit glitchy. 

Let me explain you what my cell contains: It contains all the possible component and I hidden the components which are not needed in cellForRowAtIndexPath.

I want to understand, is there a better to work with OAStackView and UITableViewCell.

Thanks

**Comment by harlanhaskins** [comment]
That's a very well-known quirk with UITableViewCell automatic sizing in iOS 8, and not related to OAStackView. http://stackoverflow.com/questions/27996438/jerky-scrolling-after-updating-uitableviewcell-in-place-with-uitableviewautomati

**Comment by mthole-old** [comment]
Suggest closing this issue.

**Comment by nsomar** [comment]
@mthole Yep, I will close it now!
