### ISSUE TITLE
OAStackView arrangedSubviews always return 0

### ISSUE THREAD

**Issue by chika-kasymov** [oarrabi/OAStackView#41]
Hi!

**OAStackView** array _arrangedSubviews_ is always empty. Therefore when I try to `insertArrangedSubview:
atIndex:` the app crashes. I can add view only by using `addArrangedSubview`.

**Comment by mthole-old** [comment]
FWIW, https://github.com/oarrabi/OAStackView/pull/17 will hopefully fix this issue.

As a workaround, you may be able to inspect the stack view's `subviews` property to decide which index to insert at. No guarantees on that, though -- I've not tried personally.
