### ISSUE TITLE
New CocoaPod version

### ISSUE THREAD

**Issue by bencallis** [oarrabi/OAStackView#42]
Would it be possible to release a new CocoaPod version which includes the latest fixes (mainly layout margin support)?

**Comment by mthole-old** [comment]
+1. For now, I've just got my app's Podfile set up like so:
`pod 'OAStackView', :git => 'https://github.com/oarrabi/OAStackView.git'`

**Comment by nsomar** [comment]
I am working on this. I will try to update the version in the upcoming days.

**Comment by bencallis** [comment]
Thanks :+1:

**Comment by bencallis** [comment]
Any update?

**Comment by delebedev** [comment]
as per my comment here: https://github.com/oarrabi/OAStackView/issues/30
new tag is 0.2.0, podspec currently waits to be pushed by maintainer

**Comment by phatmann** [comment]
@mthole, why not just use the `:head` option in your Podfile?

```
pod 'OAStackView', :head
```

**Comment by mthole-old** [comment]
@phatmann I think that'd do the same thing. :+1:

**Comment by anivaros** [comment]
@phatmann :head not working for me -- installs "Head based on 0.1.0" version

**Comment by phatmann** [comment]
That is a confusing message. It shows whatever version is in the current Podspec file, which is still "0.1.0". But the option is working for you.

**Comment by chipsnyder** [comment]
Any update on when 0.2.0 will be pushed to cocoapods?

**Comment by delebedev** [comment]
@chipsnyder just pushed, please check if 0.2.0 works for you
