### ISSUE TITLE
Example use in UIScrollView

### ISSUE THREAD

**Issue by hokster7** [oarrabi/OAStackView#44]
It would be great if this project would demonstrate how you could dynamically add more subviews and cause the OAStackView to grow.

**Comment by Lipe991** [comment]
Yes please  provide some example

**Comment by bencallis** [comment]
Why not just embedded the StackView in a scrollview (providing you get your constraints correct) it will just work.

**Comment by delebedev** [comment]
@Lipe991, @bencallis is right: stackview can be placed in scroll view as any other view with valid intrinsic content size (height in particular). Please refer to apple tech note: https://developer.apple.com/library/ios/technotes/tn2154/_index.html
