### ISSUE TITLE
issue with size classes...

### ISSUE THREAD

**Issue by stallent** [oarrabi/OAStackView#45]
When i use OAStackView in a universal nib/storyboard it works great, but if i add any views anywhere (related to stackView or not) that are only installed in certain size classes, OAStackView won't render properly.  Anyone else seen this and/or have a workaround?

**Comment by stallent** [comment]
if i implement traitCollectionDidChange: in OAStackView and then call layoutArrangedViews it seems to fix the issue

**Comment by delebedev** [comment]
@stallent can you provide small example project for this case, please?

**Comment by stallent** [comment]
No need. It reproduces in the example project. Simply select the StackView in the main storyboard and add a size class to it (Regular,Regular for example). You will notice the initial rendering is incorrect. Once you click buttons it fixes itself but the issue is layoutArrangedViews never gets called once you add a size class to the view in the nib.

**Comment by delebedev** [comment]
@stallent I've added size class and it looks fine for me. Can you please if the issue still exists in 0.2.0 tag?

**Comment by stallent** [comment]
Just tried. Still there.  Steps to reproduce... Open example.  Select the stackView instance in the storyboard and add this:

![screen shot 2015-09-28 at 10 37 12 am](https://cloud.githubusercontent.com/assets/310778/10140443/1b4ada00-65cd-11e5-80d6-5f2934bfcbb6.png)

Run in simulator and initial rendering becomes this: (which isn't correct)

<img width="503" alt="screen shot 2015-09-28 at 10 36 50 am" src="https://cloud.githubusercontent.com/assets/310778/10140459/2ef5808c-65cd-11e5-8cfd-707ff7c15cd8.png">

As I mentioned initially, the timing of when the view gets sized is different when you add a sizeClass and layoutArrangedViews is getting called too early.

**Comment by delebedev** [comment]
@stallent thanks a lot for this, now I'm finally managed to reproduce it

**Comment by delebedev** [comment]
@stallent fixed now :+1:

**Comment by stallent** [comment]
Thank you!  Looks great!
