### ISSUE TITLE
Add descriptive names to values in IB

### ISSUE THREAD

**Issue by GavinDBrown** [oarrabi/OAStackView#46]
OAStackView:
![screen shot 2015-09-02 at 1 27 53 pm](https://cloud.githubusercontent.com/assets/5473682/9643379/71f0f2f6-5176-11e5-9c54-ee3572a4c364.png)

StackView:
<img width="604" alt="screen shot 2015-09-02 at 1 28 35 pm" src="https://cloud.githubusercontent.com/assets/5473682/9643394/8f624326-5176-11e5-9a70-20cc5f478f9f.png">

In OAStackView its unclear what an axis value of a number means.

**Comment by bencallis** [comment]
As far as I know this can not be done with IBInspectable.

> You can attach the IBInspectable attribute to any property in a class declaration, class extension, or category for any type that’s supported by the Interface Builder defined runtime attributes: boolean, integer or floating point number, string, localized string, rectangle, point, size, color, range, and nil.

**Comment by delebedev** [comment]
@bencallis is right, currently it is not possible.
