### ISSUE TITLE
how to set OAStackView's subviews's spacing ?

### ISSUE THREAD

**Issue by wy19901227** [oarrabi/OAStackView#50]

**Comment by delebedev** [comment]
There is `@property(nonatomic) IBInspectable CGFloat spacing;` property for this

**Comment by wy19901227** [comment]
I want to set the first view to the secondView's spacing .not the the stackView's spacing . what I mean can I set the subView's spacing not equal?

**Comment by delebedev** [comment]
@wy19901227 it is not possible with `UIStackView` (and `OAStackView`) view itself.
However, you can set spacing to 0 and insert container views with specific height between your views:

| your view |
| --- |
| container with height 10 |
| your second view |
| container with height 20 |

etc.

**Comment by wy19901227** [comment]
UIStackview can not .but I think you can make it possible.Do you think it need?

发自我的 iPhone

**Comment by delebedev** [comment]
Unfortunately no, because the idea behind `OAStackView` is to exactly replicate `UIStackView`

**Comment by nsomar** [comment]
I will be closing this issue as its not compatible with UIStackView. Sorry for that but I don't think we should diverge from UIStackView behaviour.

**Comment by UcanUup** [comment]
In iOS 11 it is possible to customize the spacing after any of the arranged subviews of a stack view. I think OAStackView can make it possible
