### ISSUE TITLE
iOS9: UIStackView is horizontal by default, OAStackView is vertical

### ISSUE THREAD

**Issue by delebedev** [oarrabi/OAStackView#51]
Looks like breaking change, but if we want smooth transition from OA to UI version they should be the same.

**Comment by ghost** [comment]
Any update on this?
Still noticing it remains the same.

**Comment by delebedev** [comment]
@oarrabi need your input here, issue is really straightforward but will require Major version bump since it will break all the apps

**Comment by harlanhaskins** [comment]
I really don't like changing the default axis. But we have to.

**Comment by delebedev** [comment]
@harlanhaskins thanks for your input, looks like good change for 1.0 release! :trollface:

**Comment by delebedev** [comment]
Fixed in `1.0.0` version

**Comment by coridn** [comment]
As an FYI, the header for OAStackView still says the default is Vertical.

Through me for a loop when I upgraded my pods and none of my views worked anymore.  May want to consider updating that as well.

**Comment by delebedev** [comment]
@coridn nice catch, fixed here https://github.com/oarrabi/OAStackView/commit/c606348cbf7f4dc40f87e841462504cc0c4e6cb1
