### ISSUE TITLE
build in xcode7

### ISSUE THREAD

**Issue by wy19901227** [oarrabi/OAStackView#52]
![e7a601d5-fc34-4939-a921-d35c8f8da398](https://cloud.githubusercontent.com/assets/8086633/9989338/28aa0808-608a-11e5-9854-89d55b6edf13.png)

**Comment by delebedev** [comment]
builds for me without any issues Are you using cocoapods/cartage for integration?

**Comment by wy19901227** [comment]
I download your demo.

**Comment by delebedev** [comment]
@wy19901227 it works for me, did you run `pod install` inside example project folder?

**Comment by nsomar** [comment]
@wy19901227 I am closing this issue since there have been no feedback from your side.
Please feel free to reopen it if the issue persists.
