### ISSUE TITLE
Any chance of a translation from axis to axisValue (et al). 

### ISSUE THREAD

**Issue by oliverfoggin** [oarrabi/OAStackView#57]
Currently in IB you have to set axisValue and so on.

Except there is nothing anything that tells you what the values actually are.

It would take 5 mins to add documentation to these values.

Thanks

**Comment by delebedev** [comment]
@oliverfoggin you are right, it is pretty easy addition. Can you make PR please? :smiley:

**Comment by neilbilly** [comment]
@oliverfoggin @garnett: I was just trying to use OAStack today and got stuck on this (http://stackoverflow.com/q/33752916/632735?sem=2); what are the acceptable values for the axis?

**Comment by delebedev** [comment]
@neilbilly since IB does not really support "enums" as IBInspectable properties, you have to set 0 or 1 in `axisValue` in IB.

**Comment by neilbilly** [comment]
Ah right, got it! Thanks @garnett  :+1: :smile:

**Comment by nsomar** [comment]
Will be closing this as there isn't a clear solution for now.
