### ISSUE TITLE
Appending elements to an empty OAStackView looses top constraint

### ISSUE THREAD

**Issue by ULazdins** [oarrabi/OAStackView#59]
Consider this example:

``` swift
let stackView = OAStackView()
for view in view {
    stackView.addArrangedSubview(view)
}
```

As a result of this code the OAStackView has lost constraint between self and first subview.

As far as I understand, the part responsible for this is in OAStackView.h:198

``` objective-c
NSArray *constraints = [self constraintsBetweenView:self andView:previousView inAxis:self.axis];
[self removeConstraints:constraints];
```

When adding second subview, it removes constraints from the first subview, including OAStackView-to-first-subview constraints and never sets them back.

**Comment by m1entus** [comment]
This was fixed in 0.2.0 !
