### ISSUE TITLE
OAStackView is very slow.

### ISSUE THREAD

**Issue by shiratsu** [oarrabi/OAStackView#61]
I would like to use OAStackView.
I am creating such an attaching view.
I am checking on simulator.
But it is very slow.
To open this view takes around 8 seconds.
According to my investigating,,,to use several module(uiview,uilabel and uiimageview) take a long time such a 8 seconds.

are there way how to solve it?
![2015-10-16 19 56 05](https://cloud.githubusercontent.com/assets/918490/10540179/abacc3ac-7440-11e5-9a4a-1d61af26e87d.png)

**Comment by delebedev** [comment]
Can you please attach time profiler screenshot showing what exactly is "slow"? View inspector screenshot with view hierarchy might also help

**Comment by shiratsu** [comment]
Sure.I wonder you could check the following log

```
----------------------
shotworks_for_ph2_by_swift.PushSettingVCL
loadView()
Optional(2015-10-17T14:49:32.906+0900)
----------------------
----------------------
shotworks_for_ph2_by_swift.PushSettingVCL
viewDidLoad()
Optional(2015-10-17T14:49:41.685+0900)
----------------------
```

It took 9 seconds from 'loadview' to 'viewDidLoad'.
I also attached hierarchy.

<img width="1189" alt="2015-10-17 14 53 38" src="https://cloud.githubusercontent.com/assets/918490/10557262/79cf1c46-74df-11e5-891f-18414e936a40.png">

**Comment by shiratsu** [comment]
I have updated program.
I attached hierarchy again.
I am using 3 oastackview.
<img width="1385" alt="2015-10-17 18 06 13" src="https://cloud.githubusercontent.com/assets/918490/10557950/fbba9810-74f9-11e5-9a3a-b61f73469fb4.png">

**Comment by bencallis** [comment]
Have you profiled it in instruments using the time profiler?

**Comment by shiratsu** [comment]
Oh,I see.I have not used the time profiler at this time.So I will try it.

**Comment by nsomar** [comment]
@shiratsu any update on this?

**Comment by shiratsu** [comment]
Sorry,please wait.I will post result within end of this year.

**Comment by shiratsu** [comment]
I'm sorry for very late replying.
I have checked it.
On iOS8,xcode 7.1,Swift 2.1 Custom UIView is very slow.

My custom view and also OAStackView are slow.
'initWithCoder method' is very slow.
I attached capture of time profiler.
![2015-12-08 12 16 05](https://cloud.githubusercontent.com/assets/918490/11646870/7e4e4492-9da5-11e5-808c-b67baf93d84a.png)

**Comment by shiratsu** [comment]
I attached another capture.
![2015-12-08 13 02 44](https://cloud.githubusercontent.com/assets/918490/11647483/0a45cafa-9dac-11e5-9d0d-b5696c3bbded.png)

**Comment by shiratsu** [comment]
I might get answer.
In iOS8-Xcode7,I am using 'HiraginoSans' as custom font.
But this font name is not available on iOS8.
It is from iOS9.
So,My application have taken  a much time for downloading above font.

I'm sorry.Maybe,OAStackView does not have relation about slow loading.
