### ISSUE TITLE
NSMutableArray should not be declared as copy

### ISSUE THREAD

**Issue by ZevEisenberg** [oarrabi/OAStackView#65]
See here: https://github.com/oarrabi/OAStackView/blob/3569aad354210064de99a2f401ad9167fd358eba/Pod/Classes/OAStackView.m#L18

``` objc
@property(nonatomic, copy) NSMutableArray *mutableArrangedSubviews;
```

In the code, this is only ever assigned via `_mutableArrangedSubviews`, so it doesn't cause problems. But if it is ever assigned via dot syntax, it will be assigned via a synthesized setter that looks something like this:

``` objc
- (void)setMutableArrangedSubviews:(NSMutableArray *)mutableArrangedSubviews
{
    _mutableArrangedSubviews = [mutableArrangedSubviews copy];
}
```

`_mutableArrangedSubviews` is now of type `NSArray`, not `NSMutableArray`, and this code will crash if something tries to mutate it.

The fix:

``` objc
@property(nonatomic, strong) NSMutableArray *mutableArrangedSubviews;
```

**Comment by nsomar** [comment]
I agree with your fix, can you please submit a PR with this fix?

**Comment by nsomar** [comment]
Sorry I didn't see the PR, I am viewing it now.
