### ISSUE TITLE
last pod errors support Xcode 6.4

### ISSUE THREAD

**Issue by dimohamdy** [oarrabi/OAStackView#69]
❌  /Users/greenhouse/tmpM4MB54/Pods/OAStackView/Pod/Classes/OAStackView.h:87:53: expected '>'
@property(nonatomic,readonly,copy) NSArray<__kindof UIView *> *arrangedSubviews;
❌  /Users/greenhouse/tmpM4MB54/Pods/OAStackView/Pod/Classes/OAStackView.h:87:53: interface type cannot be statically allocated
@property(nonatomic,readonly,copy) NSArray<__kindof UIView *> *arrangedSubviews;
                                                    ^
❌  /Users/greenhouse/tmpM4MB54/Pods/OAStackView/Pod/Classes/OAStackView.h:87:59: expected ';' at end of declaration list
@property(nonatomic,readonly,copy) NSArray<__kindof UIView *> *arrangedSubviews;
                                                          ^
❌  /Users/greenhouse/tmpM4MB54/Pods/OAStackView/Pod/Classes/OAStackView.h:87:61: expected identifier or '('
@property(nonatomic,readonly,copy) NSArray<__kindof UIView *> *arrangedSubviews;
                                                            ^
❌  /Users/greenhouse/tmpM4MB54/Pods/OAStackView/Pod/Classes/OAStackView.h:108:60: expected '>'
- (instancetype)initWithArrangedSubviews:(NSArray<__kindof UIView *> *)views NS_DESIGNATED_INITIALIZER;
                                                         ^
  ❌  /Users/greenhouse/tmpM4MB54/Pods/OAStackView/Pod/Classes/OAStackView.h:108:60: expected ')'
- (instancetype)initWithArrangedSubviews:(NSArray<__kindof UIView *> *)views NS_DESIGNATED_INITIALIZER;

❌  /Users/greenhouse/tmpM4MB54/Pods/OAStackView/Pod/Classes/OAStackView.h:108:72: interface type 'NSArray' cannot be passed by value; did you forget \* in 'NSArray'?
- (instancetype)initWithArrangedSubviews:(NSArray<__kindof UIView *> *)views NS_DESIGNATED_INITIALIZER;
                                                                     ^

This errors in the last pod 

pod 'OAStackView', :git => 'https://github.com/oarrabi/OAStackView.git'

**Comment by nsomar** [comment]
What version of Xcode are you using? at the moment since OAStackView is using generics then Xcode 7 is required.

**Comment by dimohamdy** [comment]
xcode 6.4 can i get old version

**Comment by dimohamdy** [comment]
i fix it by 
pod 'OAStackView', :git => 'https://github.com/oarrabi/OAStackView.git', :commit => 'a49dc63'
