### ISSUE TITLE
Bump a version from master to 0.3.0

### ISSUE THREAD

**Issue by m1entus** [oarrabi/OAStackView#73]
Please bump a pod spec version to newest one.

**Comment by delebedev** [comment]
Hi @m1entus, there is at least two interesting PRs hanging, I hope me and @oarrabi will review and merge them and release new version after that.

**Comment by delebedev** [comment]
@m1entus 0.3.0 is live (it does not include your PR, I'm making final preparations to release 1.0.0 version since it would have minor but breaking change https://github.com/oarrabi/OAStackView/issues/51
