### ISSUE TITLE
`arrangedSubviews` is not behaving as expected. 

### ISSUE THREAD

**Issue by mojtabacazi** [oarrabi/OAStackView#78]
From [Apple's doc](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIStackView_Class_Reference/#//apple_ref/occ/instp/UIStackView/arrangedSubviews):

> The stack view ensures that the arrangedSubviews array is always a subset of its subviews array. Therefore, whenever the addArrangedSubview: method is called, the stack view adds the view as a subview, if it is not already. Whenever an arranged view’s removeFromSuperview method is called, the stack view removes the view from its arrangedSubview array.

**Comment by atkit** [comment]
I've just found it to be true.
