### ISSUE TITLE
Importing file error/Can't build Objective-C module

### ISSUE THREAD

**Issue by ilendemli** [oarrabi/OAStackView#90]
The extensions are using `#import <OAStackView/OAStackView.h>` to import the header files which causes an error while compiling, change all 3 extensions to use `#import "OAStackView.h"` to fix the issue.

**Comment by wowbroforce** [comment]
I had the same issue only with this pod after updating to cocoapods 1.0. Deleting derived data solved it without changing extensions

**Comment by jjulian** [comment]
Deleting derived data worked for me too.
